rapidsai/notebooks

dockerhub/README.md
mortgage/E2E.ipynb

Updating links and double checking READMEs

[REVIEW] Updates to READMEs after launch of demos site

---

README.md
cuml/README.md

Readme updates for cuml notebooks

[REVIEW] cuml notebooks readme updates

---

cuml/dbscan_demo.ipynb
cuml/knn_demo.ipynb
cuml/linear_regression_demo.ipynb
cuml/pca_demo.ipynb
cuml/ridge.ipynb
cuml/tsvd_demo.ipynb

Normally I would be working out of my own fork, but as a result of constraints on my time today, I just pushed my own branch directly to rapidsai/notebooks.

Adding notebooks from cuml so that they can be removed from cuml

---

cuml/sgd_demo.ipynb

[REVIEW] sgd demo notebook

---

cuml/linear_regression_demo.ipynb
cuml/ridge_regression_demo.ipynb
cuml/sgd_demo.ipynb

[REVIEW] linear and ridge regression demo notebook 

---

blogs/Regression Blog 1 Notebook.ipynb

blog from notebook

---

cuml/sgd_demo.ipynb

removing matplotlib import from sgd_demo notebook

---

cuml/linear_regression_demo.ipynb
cuml/ridge_regression_demo.ipynb

slightly altered the code to resolve the BUG #86

[REVIEW] closes BUG #86

---

README.md
cuml/README.md

* Merging branch-0.6-release to master
* Updated README.md and cuml/README.md to match current state of notebooks.

Merging branch-0.6-release to master

---

cuml/README.md
cuml/umap_demo.ipynb

Updates to umap demo and README for umap notebook so that it provides more detailed explanations of the evaluations and expected outputs. 
Tagging @rlratzel. Hopefully we can hotfix this

[REVIEW][HOTFIX] Adding more detailed UMAP demo and updates to README

---

cugraph/Renumber.ipynb

New notebook to demonstrate the cugraph renumbering feature.

[REVIEW] Create a notebook to demonstrate vertex renumbering

---

README.md
docs/dockerhub-README.md
docs/ngc-README.md
mortgage/E2E.ipynb

This PR updates the links to the Fannie Mae dataset which are, at the present, outdated and broken.
Closes #116 and closes #119.

[REVIEW] Update link to Fannie Mae mortgage data

---

cuml/umap_demo.ipynb

Switching verbose to False for UMAP() API call

Switching verbose to False for UMAP() API call

---

CHANGELOG.md
cugraph/README.md

Added a ChangeLog to start capturing updates

[REVIEW] Added Changelog and a cuGraph README

---

docs/dockerhub-README.md
docs/ngc-README.md

updated dockerhub and ngc docs in docs folder

updated docs folder to 0.7

---

cuml/sgd_demo.ipynb

bug fix for deprecation of n_iter

Bug fix sgd

---

cuml/rf_demo.ipynb

Demo for Random Forest Classifier

[REVIEW] Random Forest Demo

---

cuml/linear_regression_demo.ipynb
cuml/ridge_regression_demo.ipynb
cuml/sgd_demo.ipynb

removed the line used to select a GPU to run the notebooks

[REVIEW] [HOTFIX] Remove the code to select a GPU

---

cudf/notebooks_numba_cuDF_integration.ipynb

changed the text

---

README.md

added 2 notebooks for cuDF and their description

Update README.md for cudf notebooks

---

cugraph/SSSP.ipynb

Updated to show new SSSP features and output complete paths

[REVIEW] New SSSP notebook

---

cuml/dbscan_demo.ipynb
cuml/holtwinters_demo.ipynb
cuml/kmeans_demo.ipynb
cuml/nearest_neighbors_demo.ipynb
cuml/pca_demo.ipynb
cuml/random_forest_mnmg_demo.ipynb
cuml/umap_demo.ipynb

- DBSCAN notebook was not liking the new cuml.make_blobs for some reason. Went ahead and removed it from k-means as well. Also adjusting the random_state for k-means, since it was causing incorrect results (will follow up with Kamesh on this one). 
- Using sklearn.datasets.make_blobs in k-means notebook just to play it safe
- Adding some docs to nearest nieghbors explaining the discrepancy in results from sklearn and pointing to FAISS wiki. 
- Fixing / updating UMAP notebook.

[REVIEW] Fixing some notebooks that broke from cuml.make_blobs bug.

---

cudf/notebooks_Apply_Operations_in_cuDF.ipynb

Reduce size of final example by half

---

CHANGELOG.md
cudf/notebooks_Apply_Operations_in_cuDF.ipynb
cudf/notebooks_numba_cuDF_integration.ipynb

Updated imports to match current cudf, cleaned up notebook text.

Updated imports to match current cudf, cleaned up notebook text.

---

cuml/tsne_demo.ipynb

Refactored the original long TSNE demo to follow along the lines of other cuML demos ( specifically UMAP :) )

TSNE Basic Demo

---

cugraph/SSSP.ipynb
cuml/kmeans_demo_mnmg.ipynb

Auto-merge triggered by push to `branch-0.10` that creates a PR to keep `branch-0.11` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.10 to branch-0.11 [skip ci]

---

cuml/kmeans_demo.ipynb

Updated the Kmeans demo notebook to solve the plt.scatter  issue
solves the issue https://github.com/rapidsai/cuml/issues/1365

[REVIEW] Updated kmeans notebook

---

README.md

Update README.md to point people to contrib sooner (removing contrib from pinned)

---

README.md

Corrections to last updates
added folders

Corrections to cugraph README.md

---

cuml/metrics_demo.ipynb

Updated the path for sklearn trustworthiness

[REVIEW] Bug fix for the metrics demo notebook

---

cudf/notebooks_numba_cuDF_integration.ipynb

Pass GPU array by reference instead of by copy in this demo notebook.

.to_gpu_array -> .values pass by reference

---

cudf/notebooks_Apply_Operations_in_cuDF.ipynb
cudf/notebooks_numba_cuDF_integration.ipynb

[REVIEW] Minor updates to cudf notebooks for 0.12

---

cuml/umap_demo_graphed.ipynb

Auto-merge triggered by push to `branch-0.12` that creates a PR to keep `branch-0.13` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.12 to branch-0.13 [skip ci]

---

.gitmodules
clx
cudf
cugraph
cuml
cusignal
cuspatial
cuxfilter
xgboost

Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

---

.gitmodules

Updated to clone submodules from branch-0.14.

Update submodules to branch-0.14

---

.gitmodules

This PR updates the submodule branches to align with the current RAPIDS version.

Update submodule branches

---

.gitmodules

Updating to branch-0.16 submodules. Nightly testing jobs automatically update the specific commits for accurate testing.

[REVIEW] Update submodule branches

---

.gitmodules

Simply updates all of the submodules to `branch-0.18`

Update .gitmodules to v0.18

---

README.md

Update XGBoost link to point to 0.17, instead of 0.16

Update XGBoost link to point to 0.17

---

README.md
update.sh

Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

---

.gitmodules

This PR updates the submodule branches for 0.19

Update submodules for 0.19

---

.gitmodules

Syncs the submodules with new CalVer versioning.

[REVIEW] FIX Update submodule branches

---

.gitmodules

Only critical/hotfix level issues should be merged into `branch-21.08` until release (merging of this PR).
- Enable a means to merge `branch-21.08` into `main` for the release

[RELEASE] notebooks v21.08

---

test/nbtest.sh
test/nbtestlog2junitxml.py
test/test.sh

This PR includes the following changes:
- Updates submodules to latest commit on `branch-21.08` of repos (4fe8d20)
- Copies over existing notebook test scripts from [rapidsai/docker](https://github.com/rapidsai/docker) repo (d25d39e)
- Updates scripts to make them usable in `rapidsai/docker` and also DLFW containers (cdaf7e9)
- Mostly just updated paths from relative to absolute
- Also removed some extraneous/unnecessary code
The reason for this PR is to ensure that this repo includes any scripts necessary to test the notebooks.

Add test scripts

---

test/test.sh

This PR adds `ktruss.ipynb` to the ignore list.

Add ktruss.ipynb to ignore list

---

test/test.sh

This PR merges the latest `branch-21.08` changes into `main`.

[HOTFIX] Merge `branch-21.08` into `main`

---

test/test.sh

This PR merges the latest `branch-21.08` changes into `branch-21.10`.

Merge `branch-21.08` into `branch-21.10`

---

cudf
cuspatial

Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

---

.gitmodules
README.md

Only critical/hotfix level issues should be merged into `branch-22.04` until release (merging of this PR).
- Enable a means to merge `branch-22.04` into `main` for the release

[RELEASE] notebooks v22.04

---

.gitmodules
README.md

Only critical/hotfix level issues should be merged into `branch-22.06` until release (merging of this PR).
- Enable a means to merge `branch-22.06` into `main` for the release

[RELEASE] notebooks v22.06

---

cuspatial

Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

---

.gitmodules
README.md
cuspatial

Only critical/hotfix level issues should be merged into `branch-22.08` until release (merging of this PR).
- Enable a means to merge `branch-22.08` into `main` for the release

[RELEASE] notebooks v22.08

---

.gitmodules
README.md

Only critical/hotfix level issues should be merged into `branch-22.10` until release (merging of this PR).
- Enable a means to merge `branch-22.10` into `main` for the release

[RELEASE] notebooks v22.10

---

.gitmodules
README.md

Only critical/hotfix level issues should be merged into `branch-22.12` until release (merging of this PR).
- Enable a means to merge `branch-22.12` into `main` for the release

[RELEASE] notebooks v22.12

---

cudf

Updates notebooks for cuDF, requested by @taureandyernv. Follow-up to https://github.com/rapidsai/cudf/pull/12128.

Update cudf notebooks.

---

.gitmodules
clx

This PR includes the following changes:
- removes the `clx` submodule
- fixes the `cuml` SHA, which was messed up from our recent force push

Remove `clx` & Fix `cuml`
